<?php
/**
 * PHP Version 5 and above
 *
 * Main script
 *
 * @category  PHP_Chat
 * @package   PHP_Atomchat
 * @author    P H Claus <phhpro@gmail.com>
 * @copyright 2015 - 2019 P H Claus
 * @license   https://www.gnu.org/licenses/gpl-3.0.en.html GPLv3
 * @version   GIT: Latest
 * @link      https://github.com/phhpro/atomchat
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */


$ver = "20190318";

/**
 ***********************************************************************
 *                                                           First Run *
 ***********************************************************************
 */

if (isset($run) && $run < 1) {
    echo "FATAL: Cannot write configuration! Script halted.";
}

/**
 ***********************************************************************
 *                                                      Default Config *
 ***********************************************************************
 */

$cfg_dat = "./config.php";

//** Static
$cfg_txt = "<?php\n" .
           "//** Generated by Atomchat v$ver " . date('c') . "\n" .
           "\$lang=\"lang\";\n" .
           "\$theme=\"theme\";\n" .
           "\$tmp=\"tmp\";\n" .
           "\$log=\"./\$tmp/atomchat_\".date('Y-m-d').\".html\";\n" .
           "\$emo_dat=\"emo.dat\";\n" .
           "\$dt=date('Y-m-d H:i');\n";

//** Dynamic with pre-filled defaults -- editable on superuser screen
if (!is_file($cfg_dat)) {
    $cfg_txt .= "\$su_pfx=\"atom\";\n" .
                "\$su_sfx=\"chat\";\n" .
                "\$page=\"PHP Atomchat\";\n" .
                "\$meta_d=\"PHP Atomchat Demo\";\n" .
                "\$meta_k=\"PHP Atomchat Demo\";\n" .
                "\$lc=\"en\";\n" .
                "\$th=\"light\";\n" .
                "\$th_m=1;\n" .
                "\$char=512;\n" .
                "\$emo=1;\n" .
                "\$out=0;\n" .
                "\$out_max=15;\n" .
                "\$rate=15;\n" .
                "\$rn_max=900;\n" .
                "\$rn_min=100;\n" .
                "\$up=1;\n" .
                "\$up_max=1000000;\n" .
                "\$tn=100;\n" .
                "\$type=array('7z','aif','aiff','au','avi','bmp'," .
                "'bz','bz2','doc','docx','gz','m4a','m4v','mid'," .
                "'mov','mp3','mp4','mpeg','mpg','odt','oga','ogg'," .
                "'ogv','pdf','qt','rar','svg','tgz','txt','wav'," .
                "'xz','z','zip');\n" .
                "\$rm=1;\n" .
                "\$rm_max=1;\n";

    file_put_contents($cfg_dat, $cfg_txt);
    $run ++;
    header("Location: #WELCOME");
    exit;
}

/**
 ***********************************************************************
 *                                                        Dependencies *
 ***********************************************************************
 */

require $cfg_dat;

if (!is_dir($lang)) {
    $exit = "Missing language folder!";
} elseif ($up === 1 && !is_dir($tmp) && mkdir($tmp) === false) {
    $exit = "Cannot create upload folder!";
} else {

    if ($emo === 1 && is_file($emo_dat)) {
        $emo_la = array();
    } else {
        $exit = "Missing emoji definition!";
    }
}

if (isset($exit) && $exit !== "") {
    echo "$exit Script halted.";
    exit;
}

/**
 ***********************************************************************
 *                                                              Basics *
 ***********************************************************************
 */

ob_start();
header_remove('X-Powered-By');
$lock  = "./$tmp/su.lock";
$init  = "                <div class=\"item_log\">" .
         "LOG INIT $dt</div>\n";
$cval  = time() + (86400 * 30);
$su    = $su_pfx . $su_sfx;
$lc_ls = glob("$lang/*.php");
$th_ls = glob("$theme/*.css");
sort($lc_ls);
sort($th_ls);
sort($type);

/**
 ***********************************************************************
 *                                                    Delete old files *
 ***********************************************************************
 */

if ($rm === 1) {
    $rm_now = 60 * 60 * 24 * $rm_max;

    foreach (new DirectoryIterator($tmp) as $item) {

        if ($item -> isDot()) {
            continue;
        }

        if ($item -> isFile()
            && time() - $item -> getMTime() >= $rm_now
        ) {
            unlink($item -> getRealPath());
        }
    }

    unset($item);
}

/**
 ***********************************************************************
 *                                                             Credits *
 ***********************************************************************
 */

$cr = "                <ul>\n" .
      "                    <li>earabic\n" .
      "                        <ul>\n" .
      "                            <li>" .
      "Fixes Arabic translation</li>\n" .
      "                        </ul>\n" .
      "                    </li>\n" .
      "                    <li>geany.org\n" .
      "                        <ul>\n" .
      "                            <li>" .
      "Excellent lightweight IDE</li>\n" .
      "                        </ul>\n" .
      "                    </li>\n" .
      "                    <li>github.com\n" .
      "                        <ul>\n" .
      "                            <li>" .
      "Source repository</li>\n" .
      "                        </ul>\n" .
      "                    </li>\n" .
      "                    <li>schouten.io\n" .
      "                        <ul>\n" .
      "                            <li>" .
      "Initial Dutch translation</li>\n" .
      "                        </ul>\n" .
      "                    </li>\n" .
      "                    <li>stackoverflow.com\n" .
      "                        <ul>\n" .
      "                            <li>" .
      "Inspiriation</li>\n" .
      "                        </ul>\n" .
      "                    </li>\n" .
      "                    <li>translate.google.com\n" .
      "                        <ul>\n" .
      "                            <li>" .
      "Machine translation</li>\n" .
      "                        </ul>\n" .
      "                    </li>\n" .
      "                </ul>\n" .
      "                <p>et al</p>\n";

/**
 ***********************************************************************
 *                                                           Functions *
 ***********************************************************************
 */

if (get_cfg_var('session.use_strict_mode') !== 1) {
    ini_set('session.use_strict_mode', 1);
}

/**
 * Function sessionstat()
 *
 * @return bool session status
 */
function sessionstat()
{
    if (php_sapi_name() !== 'cli'
        && version_compare(phpversion(), '5.4.0', '>=')
    ) {
        return session_status()
            === PHP_SESSION_ACTIVE ? true : false;
    } else {
        return session_id() === '' ? false : true;
    }

    return false;
}

if (sessionstat() === false && !session_start()) {
    echo "Cannot create session! Script halted.";
    exit;
} else {
    session_start();
}

/**
 * Function b64()
 *
 * @param string $src source
 *
 * @return string data blob
 */
function b64($src)
{
    $ext = pathinfo($src, PATHINFO_EXTENSION);
    $get = file_get_contents($src);
    $str = "\"\ndata:image/" . $ext .
           ";base64," . base64_encode($get) . "\" ";
    return $str;
}

$b64 = array('gif', 'jpeg', 'jpg', 'png');

/**
 * Function go()
 *
 * @param string $tag target
 *
 * @return string hashtag reference
 */
function go($tag)
{
    global $host;
    header("Location: $host#$tag");
    exit;
}

/**
 ***********************************************************************
 *                                                                 URL *
 ***********************************************************************
 */

$pro = "";

if (isset($_SERVER['HTTPS']) && 'on' === $_SERVER['HTTPS']) {
    $pro = "s";
}

$host = "http$pro://" . $_SERVER['HTTP_HOST'] .
        "/" . basename(getcwd()) . "/";

/**
 ***********************************************************************
 *                                                                 Log *
 ***********************************************************************
 */

if (!is_file($log)) {
    file_put_contents($log, $init);
}

/**
 ***********************************************************************
 *                                                            Language *
 ***********************************************************************
 */

/*
 * Asian scripts in page language meta seem to break fonts, formatting,
 * and colour emojis. Can't test on non-Asian system but hard-linking
 * static Western locale fixes the issue.
 */

$lc_id = "en";

//** Try auto detect
if (isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
    $lc_hal = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
    $lc_usr = $lc_hal;

    foreach ($lc_ls as $item) {
        $item = str_replace("$lang/", "", $item);
        $item = str_replace(".php", "", $item);

        if (strpos($item, $lc_usr) === false) {
            continue;
        } else {
            $lc_use = $lc_usr;
        }
    }

    unset($item);
}

//** Select from settings screen
if (isset($_POST['language'])) {
    $lc_use = htmlentities($_POST['lc_use'], ENT_QUOTES, 'UTF-8');

    if ($lc_use !== "") {

        if (isset($_COOKIE['ac_language'])) {
            setcookie('ac_language', $lc_use, $cval, '/');
            $_COOKIE['ac_language']  = $lc_use;
            $lc_use                  = $_COOKIE['ac_language'];
        } else {
            $_SESSION['ac_language'] = $lc_use;
            $lc_use                  = $_SESSION['ac_language'];
        }
    } else {
        go('EMPTY_SELECT');
    }
}

//** Link language value
if (isset($_COOKIE['ac_language'])) {
    $lc_use = $_COOKIE['ac_language'];
} elseif (isset($_SESSION['ac_language'])) {
    $lc_use = $_SESSION['ac_language'];
} elseif ($lc_use !== "") {
    $lc_use = $lc_use;
} else {
    $lc_use = $lc;
}

$lc_dat = "./" . $lang . "/" . $lc_use . ".php";

if (is_file($lc_dat)) {
    include $lc_dat;
} else {
    //** File removed -- try default
    if (isset($_COOKIE['ac_language'])) {
        setcookie('ac_language', $lc, $cval, '/');
        $lc                      = $_COOKIE['ac_language'];
        $_COOKIE['ac_language']  = $lc;
    } else {
        $_SESSION['ac_language'] = $lc;
        $lc                      = $_SESSION['ac_language'];
    }

    include "./" . $lang . "/" . $lc . ".php";

    echo "<p>The requested file is no longer available!</p>\n" .
         "<p><a href=\"$host\" title=\"Click here to try default " .
         "settings\">Click here to try default settings.</a></p>\n" .
         "<p>If that fails, and you know how to contact the site " .
         "owner, now would be a good moment.</p>";
    exit;
}

/**
 ***********************************************************************
 *                                   Select theme from settings screen *
 ***********************************************************************
 */

if (isset($_POST['theme'])) {
    $th_use = htmlentities($_POST['th_use'], ENT_QUOTES, 'UTF-8');

    if ($th_use !== "") {

        if (isset($_COOKIE['ac_theme'])) {
            setcookie('ac_theme', $th_use, $cval, '/');
            $_COOKIE['ac_theme']  = $th_use;
            $th_use               = $_COOKIE['ac_theme'];
        } else {
            $_SESSION['ac_theme'] = $th_use;
            $th_use               = $_SESSION['ac_theme'];
        }
    } else {
        go('EMPTY_SELECT');
    }
} else {

    if (isset($_COOKIE['ac_theme'])) {
        $th_use = $_COOKIE['ac_theme'];
    } elseif (isset($_SESSION['ac_theme'])) {
        $th_use = $_SESSION['ac_theme'];
    } else {
        $th_use = $th;
    }
}

$th_dat = $theme . "/" . $th_use . ".css";

/**
 ***********************************************************************
 *                                                            Save Log *
 ***********************************************************************
 */

if (isset($_POST['save'])) {
    $sav = str_replace("./$tmp/", "", $log);
    $sav = str_replace(".html", ".tmp", $sav);
    copy($log, $sav);
    $txt = "<!DOCTYPE html>\n" .
            "<html lang=\"$lc_id\">\n" .
            "    <head>\n" .
            "        <title>$sav</title>\n" .
            "        <meta charset=\"UTF-8\"/>\n" .
            "        <meta name=\"language\" " .
            "content=\"$lc_id\"/>\n" .
            "        <meta name=\"viewport\" " .
            "content=\"width=device-width, " .
            "height=device-height, initial-scale=1\"/>\n" .
            "    </head>\n" .
            "    <body>\n" .
    file_get_contents($sav) .
            "    </body>\n" .
            "</html>\n";
    file_put_contents($sav, $txt);
    header('Content-type: text/html');
    header(
        'Content-Disposition: attachment; filename="' . $sav . '"'
    );
    readfile($sav);
    unlink($sav);
    exit;
}

/**
 ***********************************************************************
 *                                 Update config from superuser screen *
 ***********************************************************************
 */

if (isset($_POST['update'])) {
    $su_pfx_new
        = htmlentities($_POST['su_pfx'], ENT_QUOTES, 'UTF-8');
    $su_sfx_new
        = htmlentities($_POST['su_sfx'], ENT_QUOTES, 'UTF-8');
    $page_new
        = htmlentities($_POST['page'], ENT_QUOTES, 'UTF-8');
    $meta_d_new
        = htmlentities($_POST['meta_d'], ENT_QUOTES, 'UTF-8');
    $meta_k_new
        = htmlentities($_POST['meta_k'], ENT_QUOTES, 'UTF-8');
    $lc_new
        = htmlentities($_POST['lc'], ENT_QUOTES, 'UTF-8');
    $th_new
        = htmlentities($_POST['th'], ENT_QUOTES, 'UTF-8');
    $th_m_new
        = htmlentities($_POST['th_m'], ENT_QUOTES, 'UTF-8');
    $char_new
        = htmlentities($_POST['char'], ENT_QUOTES, 'UTF-8');
    $emo_new
        = htmlentities($_POST['emo'], ENT_QUOTES, 'UTF-8');
    $rate_new
        = htmlentities($_POST['rate'], ENT_QUOTES, 'UTF-8');
    $out_new
        = htmlentities($_POST['out'], ENT_QUOTES, 'UTF-8');
    $out_max_new
        = htmlentities($_POST['out_max'], ENT_QUOTES, 'UTF-8');
    $rn_max_new
        = htmlentities($_POST['rn_max'], ENT_QUOTES, 'UTF-8');
    $rn_min_new
        = htmlentities($_POST['rn_min'], ENT_QUOTES, 'UTF-8');
    $up_new
        = htmlentities($_POST['up'], ENT_QUOTES, 'UTF-8');
    $up_max_new
        = htmlentities($_POST['up_max'], ENT_QUOTES, 'UTF-8');
    $rm_new
        = htmlentities($_POST['rm'], ENT_QUOTES, 'UTF-8');
    $rm_max_new
        = htmlentities($_POST['rm_max'], ENT_QUOTES, 'UTF-8');
    $tn_new
        = htmlentities($_POST['tn'], ENT_QUOTES, 'UTF-8');
    $type_del
        = htmlentities($_POST['type_del'], ENT_QUOTES, 'UTF-8');
    $type_add
        = htmlentities($_POST['type_add'], ENT_QUOTES, 'UTF-8');

    //** Prefix
    if ($su_pfx_new !== "") {
        $su_pfx_new = $su_pfx_new;
    } else {
        $su_pfx_new = $su_pfx;
    }

    //** Suffix
    if ($su_sfx_new !== "") {
        $su_sfx_new = $su_sfx_new;
    } else {
        $su_sfx_new = $su_sfx;
    }

    //** Page title
    if ($page_new !== "") {
        $page_new = $page_new;
    } else {
        $page_new = $page;
    }

    //** META description
    if ($meta_d_new !== "") {
        $meta_d_new = $meta_d_new;
    } else {
        $meta_d_new = $meta_d;
    }

    //** META keywords
    if ($meta_k_new !== "") {
        $meta_k_new = $meta_k_new;
    } else {
        $meta_k_new = $meta_k;
    }

    //** Language
    if ($lc_new !== "") {
        $lc_new = $lc_new;
    } else {
        $lc_new = $lc;
    }

    //** Theme
    if ($th_new !== "") {
        $th_new = $th_new;
    } else {
        $th_new = $th;
    }

    //** Theme multi
    if ($th_m_new !== "") {
        $th_m_new = 1;
    } else {
        $th_m_new = 0;
    }

    //** Characters max per post
    if ($char_new !== "") {
        $char_new = $char_new;
    } else {
        $char_new = $char;
    }

    //** Emoji auto conversion
    if ($emo_new !== "") {
        $emo_new = 1;
    } else {
        $emo_new = 0;
    }

    //** Refresh rate
    if ($rate_new !== "") {
        $rate_new = $rate_new;
    } else {
        $rate_new = $rate;
    }

    //** Timeout
    if ($out_new !== "") {
        $out_new = 1;
    } else {
        $out_new = 0;
    }

    //** Timeout max
    if ($out_max_new !== "") {
        $out_max_new = $out_max_new;
    } else {
        $out_max_new = $out_max;
    }

    //** Random max
    if ($rn_max_new !== "") {
        $rn_max_new = $rn_max_new;
    } else {
        $rn_max_new = $rn_max;
    }

    //** Random min
    if ($rn_min_new !== "") {
        $rn_min_new = $rn_min_new;
    } else {
        $rn_min_new = $rn_min;
    }

    //** Uploads
    if ($up_new !== "") {
        $up_new = 1;
    } else {
        $up_new = 0;
    }

    //** Uploads max size
    if ($up_max_new !== "") {
        $up_max_new = $up_max_new;
    } else {
        $up_max_new = $up_max;
    }

    //** Type delete
    if ($type_del !== "") {
        $type = array_diff($type, array($type_del));
    }

    //** Type add
    if ($type_add !== "") {
        $type[] = $type_add;
    }

    //** Thumbnail max w/h
    if ($tn_new !== "") {
        $tn_new = $tn_new;
    } else {
        $tn_new = $tn;
    }

    //** Auto remove old files
    if (!$rm_new !== "") {
        $rm_new = 1;
    } else {
        $rm_new = 0;
    }

    //** Days to keep files
    if ($rm_max_new !== "") {
        $rm_max_new = $rm_max_new;
    } else {
        $rm_max_new = $rm_max;
    }

    //** Update config
    $type_new = implode(",", $type);
    $type_new = str_replace(",", "','", $type_new);
    $cfg_txt .= "\$su_pfx=\"$su_pfx_new\";\n" .
                "\$su_sfx=\"$su_sfx_new\";\n" .
                "\$page=\"$page_new\";\n" .
                "\$meta_d=\"$meta_d_new\";\n" .
                "\$meta_k=\"$meta_k_new\";\n" .
                "\$lc=\"$lc_new\";\n" .
                "\$th=\"$th_new\";\n" .
                "\$th_m=$th_m_new;\n" .
                "\$char=$char_new;\n" .
                "\$emo=$emo_new;\n" .
                "\$rate=$rate_new;\n" .
                "\$out=\"$out_new\";\n" .
                "\$out_max=\"$out_max_new\";\n" .
                "\$rn_max=$rn_max_new;\n" .
                "\$rn_min=$rn_min_new;\n" .
                "\$up=$up_new;\n" .
                "\$up_max=$up_max_new;\n" .
                "\$type=array('$type_new');\n" .
                "\$tn=$tn_new;\n" .
                "\$rm=$rm_new;\n" .
                "\$rm_max=$rm_max_new;\n";

    file_put_contents($cfg_dat, $cfg_txt);
    go('CONF_UPDATE');
}

//** Reset log
if (isset($_POST['reset'])) {
    unlink($log);
    file_put_contents($log, $init);
    go('LOG_RESET');
}

/**
 ***********************************************************************
 *                                                        Post message *
 ***********************************************************************
 */

$ok = 0;

if (isset($_POST['post'])) {
    $name = htmlentities($_POST['name'], ENT_QUOTES, 'UTF-8');
    $text = htmlentities($_POST['text'], ENT_QUOTES, 'UTF-8');

    if ($text !== "") {
        $_SESSION['ac_text'] = $text;
        $text                = wordwrap($text, 68);
        $ok                  = 1;

        if ($emo === 1) {
            $emo_fh = fopen($emo_dat, 'r');

            while (!feof($emo_fh)) {
                $emo_ln   = fgets($emo_fh);
                $emo_ln   = trim($emo_ln);
                $emo_ln   = explode("|", $emo_ln);
                $emo_la[] = $emo_ln;

                if (stripos($text, $emo_ln[0]) !== false) {
                    $text = trim(
                        str_replace(
                            $emo_ln[0],
                            "<span class=\"emo\">" .
                            $emo_ln[1] . "</span>",
                            $text
                        )
                    );
                }

            }

            fclose($emo_fh);
        }
    }

    if ($up === 1) {

        if (!empty($_FILES['file']['name'])) {
            $up_fh  = basename($_FILES['file']['name']);
            $up_tmp = $_FILES['file']['tmp_name'];
            $up_img = getimagesize($_FILES['file']['tmp_name']);
            $up_sz  = $_FILES['file']['size'];
            $up_to  = $tmp . "/" . $up_fh;
            $up_xt  = strtolower(pathinfo($up_to, PATHINFO_EXTENSION));
            $up_rn  = mt_rand() . "." . $up_xt;
            $up_sav = str_replace($up_fh, $up_rn, $up_to);
            $up_url = $host . $up_sav;

            if ($up_sz > $up_max) {
                go('BAD_FILESIZE');
            } else {

                if (move_uploaded_file(
                    $_FILES['file']['tmp_name'], $up_to
                ) && copy($up_to, $up_sav)
                ) {
                    $ok = 1;
                } else {
                    go('WRITE_ERROR');
                }

                unlink($up_to);
            }

            if (in_array($up_xt, $b64)) {

                if (empty($up_img)) {
                    go('INVALID_IMAGE');
                } else {
                    $up_ico = "tn_" . basename($up_sav);
                    copy($up_sav, $up_ico);

                    if ($up_xt === "jpeg" || $up_xt === "jpg") {
                        $up_src = imagecreatefromjpeg($up_ico);
                    } elseif ($up_xt === "png") {
                        $up_src = imagecreatefrompng($up_ico);
                    } elseif ($up_xt === "gif") {
                        $up_src = imagecreatefromgif($up_ico);
                    } else {
                        go('NOT_SUPPORTED');
                    }

                    $up_iw = imagesx($up_src);
                    $up_ih = imagesy($up_src);
                    $up_wh = min($tn / $up_iw, $tn / $up_ih);
                    $up_tw = ceil($up_wh * $up_iw);
                    $up_th = ceil($up_wh * $up_ih);
                    $up_tn = imagecreatetruecolor($up_tw, $up_th);

                    imagecopyresampled(
                        $up_tn, $up_src,
                        0, 0, 0, 0,
                        $up_tw, $up_th, $up_iw, $up_ih
                    );

                    if ($up_xt === "jpeg" || $up_xt === "jpg") {
                        imagejpeg($up_tn, $up_ico, 60);
                    } elseif ($up_xt === "png") {
                        imagepng($up_ico);
                    } else {
                        imagegif($up_ico);
                    }

                    $up_link = "<br/><a href=\"$up_url\" title=\"" .
                               $lc_str['open'] . "\"><img src=" .
                               chunk_split(b64($up_ico), 68) .
                               "width=\"$up_tw\" height=\"$up_th\" " .
                               "alt=\"\"/></a>";

                    imagedestroy($up_src);
                    imagedestroy($up_tn);
                    unlink($up_ico);
                }
            } elseif (in_array($up_xt, $type)) {
                $up_link = "<a href=\"$up_url\" " .
                           "title=\"" . $lc_str['open'] . "\">" .
                           basename($up_sav) . "</a>";
            } else {
                go('BAD_TYPE');
            }
        }
    }

    if ($text !== "" && $up_link === "") {
        $item = $text;
    } elseif ($text !== "" && $up_link !== "") {
        $item = $text . " " . $up_link;
    } elseif ($text === "" && $up_link !== "") {
        $item = $up_link;
    } else {
        $ok = 0;
    }

    if ($ok === 1) {
        $id_t = "item_" . time();
        $id_d = $id_t;

        $item = "                <div class=\"item\">\n" .
                "                    <div class=\"item_head\">\n" .
                "                        <span class=\"item_date\">" .
                "$dt</span> \n" .
                "                        <span onClick=\"" .
                "selectID('$id_d');\">&nbsp;&hArr;&nbsp;</span> \n" .
                "                        <span class=\"item_name\">" .
                $_SESSION['ac_name'] . "</span>\n" .
                "                    </div>\n" .
                "<pre class=\"item_text\" id=\"$id_d\">\n" .
                "$item\n" .
                "</pre>\n" .
                "                </div>\n" .
                "                <hr/>\n";

        $item .= file_get_contents($log);
        file_put_contents($log, $item);
        unset($_SESSION['ac_text']);

        if ($out === 1) {
            $_SESSION['ac_post'] = time();
        }

        go('POST');
    } else {
        go('EMPTY_POST');
    }
}

/**
 ***********************************************************************
 *                                                               Login *
 ***********************************************************************
 */

if (isset($_POST['login'])) {
    $name = htmlentities($_POST['name'], ENT_QUOTES, 'UTF-8');
    $perm = htmlentities($_POST['perm'], ENT_QUOTES, 'UTF-8');

    if (!empty($perm)) {
        $perm = 1;
    } else {
        $perm = 0;
    }

    if ($name === "") {
        go('MISSING_NAME');
    } else {

        if ($name === $su) {

            if (is_file($lock)) {
                go('ALREADY_LOGGED_IN');
            } else {
                file_put_contents($lock, "1");
                $_SESSION['ac_name'] = $su_pfx;
            }
        } else {
            $_SESSION['ac_name']
                = $name . "_" . mt_rand($rn_min, $rn_max);
        }

        $text = "                <div class=\"item_log\">$dt " .
                $_SESSION['ac_name'] . " LOGIN</div>\n";

        if (is_file($log)) {
            $text .= file_get_contents($log);
        }

        file_put_contents($log, $text);

        if (!isset($_COOKIE['ac_cookie'])) {

            if ($perm === 1) {
                setcookie('ac_cookie', 'accept', $cval, '/');

                if (count($_COOKIE) > 0) {
                    setcookie('ac_language', $lc, $cval, '/');
                    setcookie('ac_theme', $th, $cval, '/');
                    $_SESSION['ac_language'] = $_COOKIE['ac_language'];
                    $_SESSION['ac_theme']    = $_COOKIE['ac_theme'];
                }
            } else {
                $_SESSION['ac_language'] = $lc;
                $_SESSION['ac_theme']    = $th;
            }
        }

        go('LOGIN');
    }
}

/**
 ***********************************************************************
 *                                                              Logout *
 ***********************************************************************
 */

$stat = 1;

if (isset($_SESSION['ac_post'])
    && time() - $_SESSION['ac_post'] >= 60 * $out_max
) {
    $exit = "LOGOUT_INACTIVE";
} elseif (isset($_POST['quit'])) {

    if ($_SESSION['ac_name'] = $su_pfx) {

        if (is_file($lock)) {
            unlink($lock);
        }
    }

    $exit = "LOGOUT";
} else {
    $stat = 0;
}

if ($stat === 1) {
    $text  = "                <div class=\"item_log\">$dt " .
             $_SESSION['ac_name'] . " $exit</div>\n";
    $text .= file_get_contents($log);
    file_put_contents($log, $text);
    $_SESSION = array();

    if (ini_get("session.use_cookies")) {
        $para = session_get_cookie_params();
        setcookie(
            session_name(), '', time() - 42000,
            $para["path"], $para["domain"],
            $para["secure"], $para["httponly"]
        );
    }

    if (session_status() === PHP_SESSION_ACTIVE) {
        session_destroy();
    }

    go($exit);
}

/**
 ***********************************************************************
 *                                                        Begin markup *
 ***********************************************************************
 */

echo "<!DOCTYPE html>\n" .
     "<html lang=\"$lc_id\">\n" .
     "    <head>\n" .
     "        <title>$page</title>\n" .
     "        <meta charset=\"UTF-8\"/>\n" .
     "        <meta name=\"language\" content=\"$lc_id\"/>\n" .
     "        <meta name=\"description\" " .
     "content=\"$meta_d - PHP Atomchat free PHP chat scripts\"/>\n" .
     "        <meta name=\"keywords\" " .
     "content=\"$meta_k,PHP Atomchat,free PHP chat scripts\"/>\n" .
     "        <meta name=\"robots\" content=\"noodp, noydir\"/>\n" .
     "        <meta name=\"viewport\" content=\"width=device-width, " .
     "height=device-height, initial-scale=1\"/>\n" .
     "        <link rel=\"icon\" href=\"" . $host . "favicon.png\" " .
     "type=\"image/png\"/>\n" .
     "        <link rel=\"stylesheet\" " .
     "href=\"" . $host. "default.css\"/>\n" .
     "        <link rel=\"stylesheet\" href=\"$host$th_dat\"/>\n" .
     "    </head>\n" .
     "    <body>\n" .
     "        <form action=\"$host#CHAT\" name=\"chat\" " .
     "method=\"POST\" accept-charset=\"UTF-8\" " .
     "enctype=\"multipart/form-data\">\n";

/**
 ***********************************************************************
 *                                                          Navigation *
 ***********************************************************************
 */

if (isset($_SESSION['ac_name']) && $_SESSION['ac_name'] !== "") {
    echo "            <nav class=\"block\">\n" .
         "                <div id=\"mo\">\n" .

    //** Character counter
         "                    " . $lc_str['text'] . " <input " .
         "id=\"txta\" size=\"4\" value=\"$char\" disabled /> " .

         "<span class=\"emo\">&#x1F60E;</span> " .
         $lc_str['emo'] . "\n" .

    //** Emoji hover menu
         "                    <div id=\"mo_list\">\n";

    $emo_fh = fopen($emo_dat, 'r');

    while (!feof($emo_fh)) {
        $emo_ln   = fgets($emo_fh);
        $emo_ln   = trim($emo_ln);
        $emo_ln   = explode("|", $emo_ln);
        $emo_la[] = $emo_ln;
        $emo_id   = str_replace("&#x", "", $emo_ln[1]);
        $emo_id   = str_replace(";", "", $emo_id);
        $emo_id   = "emo_$emo_id";

        if ($emo_ln[0] !== "") {
            echo "                        <input type=\"text\" " .
                 "id=\"$emo_id\" class=\"emo_id\" " .
                 "value=\"$emo_ln[1]\" " .
                 "title=\"" . $emo_ln[0] . "\" " .
                 "onclick=\"emo('$emo_id');\"/>\n";
        }
    }

    fclose($emo_fh);


    echo "                    </div>\n" .
         "                </div>\n" .

    //** Text
         "                <textarea name=\"text\" id=\"text\" " .
         "rows=\"2\" cols=\"45\" maxlength=\"$char\" " .
         "title=\"" . $lc_str['text_tip'] . "\" " .
         "onkeydown=\"chars(this.form);\" " .
         "onkeypress=\"chars(this.form);\" " .
         "onkeyup=\"chars(this.form);\">";

    if ($_SESSION['ac_text'] !== "") {
        $_POST['ac_text'] = $_SESSION['ac_text'];
        echo $_SESSION['ac_text'];
    }

    echo "</textarea>\n" .
         "                <div>\n" .

    //** Name -- hidden session token
         "                    <input type=\"hidden\" name=\"name\" " .
         "value=\"" . $_SESSION['ac_name'] . "\"/>\n";

    //** Superuser
    if ($_SESSION['ac_name'] === $su_pfx) {
        echo "                    <input type=\"submit\" " .
             "name=\"su\" id=\"su\" value=\"!\" " .
             "title=\"" . $lc_str['su_open'] . "\"/>\n";
    }

    //** Quit
    echo "                    <input type=\"submit\" " .
         "name=\"quit\" id=\"quit\" value=\"x\" " .
         "title=\"" . $lc_str['quit'] . "\"/>\n" .

    //** Credits
         "                    <input type=\"submit\" " .
         "name=\"cr\" id=\"cr\" value=\"c\" " .
         "title=\"" . $lc_str['cr_tip'] . "\"/>\n" .

    //** Settings
         "                    <input type=\"submit\" " .
         "name=\"set\" id=\"set\" value=\"=\" " .
         "title=\"" . $lc_str['set_tip'] . "\"/>\n" .

    //** Save log
         "                    <input type=\"submit\" " .
         "name=\"save\" id=\"save\" value=\"v\" " .
         "title=\"" . $lc_str['save'] . "\"/>\n";

    //** Upload
    if ($up === 1) {
        echo "                    <input type=\"submit\" " .
             "name=\"upload\" id=\"upload\" value=\"+\" " .
             "title=\"" . $lc_str['up_sel'] . "\"/>\n";
    }

    //** Post
    echo "                    <input type=\"submit\" " .
         "name=\"post\" id=\"post\" value=\"&gt;\" " .
         "title=\"" . $lc_str['post'] . "\"/>\n" .
         "                </div>\n" .

    //** Repository link and JS helper
         "                <div id=\"by\">\n" .
         "                    <span></span><span></span><span></span>" .
         "&nbsp;<a href=\"https://github.com/phhpro/atomchat\" " .
         "title=\"" . $lc_str['get'] . "\">PHP Atomchat v$ver</a>\n" .
         "                </div>\n" .
         "                <script>\n" .
         "                    var char = $char;\n" .
         "                    var rate = $rate;\n" .
         "                    var data = \"$log\";\n" .
         "                </script>\n" .
         "                <script src=\"chat.js\"></script>\n" .
         "            </nav>\n";

    /**
     *******************************************************************
     *                                                  Chatlog screen *
     *******************************************************************
     */

    if (!isset($_POST['set'])
        && !isset($_POST['upload'])
        && !isset($_POST['credit'])
        && !isset($_POST['su'])
    ) {
        echo "            <article class=\"block\" id=\"push\">\n";

        if (is_file($log)) {
            include $log;
        } else {
            file_put_contents($log, $init);
            include $log;
        }

        echo "            </article>\n";
    }

    /**
     *******************************************************************
     *                                                 Settings screen *
     *******************************************************************
     */

    if (isset($_POST['set'])) {
        echo "            <article class=\"block\" id=\"settings\">\n" .
             "                <h1>" . $lc_str['set'] . "</h1>\n" .
             "                <p>" . $lc_str['set_txt'] . "</p>\n" .

        //** Language list
             "                <p>\n" .
             "                    <label for=\"lc_use\">" .
             $lc_str['lc'] . "</label>\n" .
             "                    <select name=\"lc_use\" " .
             "title=\"" . $lc_str['lc_tip'] . "\">\n" .
             "                        <option value=\"select\" " .
             "title=\"" . $lc_str['sel_tip'] . "\" selected " .
             "disabled>" . $lc_str['sel'] . "</option>\n";

        foreach ($lc_ls as $item) {
            $lc_get = file_get_contents($item);
            $lc_ln  = file($item);
            $lc_txt = $lc_ln[16];
            $lc_txt = str_replace(
                "\$lc_str['__name__']   = \"", "", $lc_txt
            );
            $lc_txt = str_replace("\";\n", "", $lc_txt);
            $lc_tip = $lc_ln[17];
            $lc_tip = str_replace(
                "\$lc_str['__text__']   = \"", "", $lc_tip
            );
            $lc_tip = str_replace("\";\n", "", $lc_tip);
            $lc_val = basename($item);
            $lc_val = str_replace(".php", "", $lc_val);

            echo "                        <option " .
                 "value=\"$lc_val\" lang=\"$lc_val\" " .
                 "title=\"$lc_tip\">" . strtoupper($lc_val) .
                 " $lc_txt</option>\n";
        }

        unset($item);

        echo "                    </select>\n" .
             "                    <input type=\"submit\" " .
             "name=\"language\" value=\"&gt;\" " .
             "title=\"" . $lc_str['apply'] . "\"/>\n" .
             "                </p>\n";

        //** Theme list
        if ($th_m === 1) {
            echo "                <p>\n" .
                 "                    <label for=\"th_use\">" .
                 $lc_str['th'] . "</label>\n" .
                 "                    <select name=\"th_use\" " .
                 "title=\"" . $lc_str['th_tip'] . "\">\n" .
                 "                        <option value=\"select\" " .
                 "title=\"" . $lc_str['sel_tip'] . "\" selected " .
                 "disabled>" . $lc_str['sel'] . "</option>\n";

            foreach ($th_ls as $item) {
                $th_val = basename($item);
                $th_val = str_replace(".css", "", $th_val);
                $th_txt = str_replace(array("-", "_"), " ", $th_val);

                echo "                        <option " .
                     "value=\"$th_val\" " .
                     "title=\"" . $lc_str['th_tip'] . " " .
                     ucwords($th_txt) . "\">" . ucwords($th_txt);

                if (isset($_COOKIE['ac_theme'])
                    && $th_val === $_COOKIE['ac_theme']
                ) {
                    echo " [x]";
                } elseif ($th_val === $_SESSION['ac_theme']) {
                    echo " [x]";
                } else {
                    //** No cookie, no session -- skip
                }

                echo "</option>\n";
            }

            unset($item);

            echo "                    </select>\n" .
                 "                    <input type=\"submit\" " .
                 "name=\"theme\" id= \"theme\" value=\"&gt;\" " .
                 "title=\"" . $lc_str['apply'] . "\"/>\n" .
                 "                </p>\n";
        }

        //** Emojis list
        if ($emo === 1) {
            echo "                <h2>" . $lc_str['emo'] . "</h2>\n" .
                 "                <p>" . $lc_str['emo_txt'] . "</p>\n" .
                 "                <p class=\"emo large\">";

            $emo_fh = fopen($emo_dat, 'r');

            while (!feof($emo_fh)) {
                $emo_ln   = fgets($emo_fh);
                $emo_ln   = trim($emo_ln);
                $emo_ln   = explode("|", $emo_ln);
                $emo_la[] = $emo_ln;

                if ($emo_ln[1] !== "") {
                    echo "<span class=\"glue\">" . $emo_ln[0] .
                         "&nbsp;" . $emo_ln[1] . "</span> ";
                }
            }

            fclose($emo_fh);

            echo "</p>\n";
        }

        //** Close settings screen
        echo "                <div class=\"close\">\n" .
             "                    <input type=\"submit\" " .
             "name=\"close\" id=\"close\" value=\"x\" " .
             "title=\"" . $lc_str['close'] . "\"/>\n" .
             "                </div>\n" .
             "            </article>\n";
    }

    /**
     *******************************************************************
     *                                                   Upload screen *
     *******************************************************************
     */

    if (isset($_POST['upload'])) {
        echo "            <article class=\"block\" id=\"uploads\">\n" .
             "                <h1>" . $lc_str['up'] . "</h1>\n" .
             "                <p>" . $lc_str['up_txt'] . "</p>\n" .
             "                <h2>" . $lc_str['type'] . "</h2>\n" .
             "                <p>";

        //** Static -- internal Base64
        foreach ($b64 as $item) {
            echo "$item ";
        }

        unset($item);

        //** Dynamic -- change from superuser screen
        foreach ($type as $item) {
            echo "$item ";
        }

        unset($item);

        echo "</p>\n" .
             "                <p>" . $lc_str['max'] .
             " $up_max</p>\n" .
             "                <p>\n" .
             "                    <label for=\"file\">" .
             $lc_str['file'] . "</label>\n" .
             "                    <input type=\"file\" name=\"file\" " .
             "id=\"file\" title=\"" . $lc_str['up_sel'] . "\"/>\n" .
             "                </p>\n" .

        //** Close upload screen
             "                <div class=\"close\">\n" .
             "                    <input type=\"submit\" " .
             "name=\"close\" id=\"close\" value=\"x\" " .
             "title=\"" . $lc_str['close'] . "\"/>\n" .
             "                </div>\n" .
             "            </article>\n";
    }


    /**
     *******************************************************************
     *                                                  Credits screen *
     *******************************************************************
     */

    if (isset($_POST['cr'])) {
        echo "            <article class=\"block\" id=\"credits\">\n" .
             "                <h1>" . $lc_str['cr'] . "</h1>\n" .
             "                <p>" . $lc_str['cr_txt'] . "</p>\n" .
             $cr .

        //** Close credits screen
             "                <div class=\"close\">\n" .
             "                    <input type=\"submit\" " .
             "name=\"close\" id=\"close\" value=\"x\" " .
             "title=\"" . $lc_str['close'] . "\"/>\n" .
             "                </div>\n" .
             "            </article>\n";
    }

    /**
     *******************************************************************
     *                                                Superuser screen *
     *******************************************************************
    */

    if (isset($_POST['su'])) {

        echo "            <article class=\"block\" id=\"super\">\n" .
             "                <h1>" . $lc_str['su'] . "</h1>\n" .
             "                <p class=\"aleft\">" .
             $lc_str['su_txt'] . "</p>" .

        //** Prefix
             "                <p>\n" .
             "                    <label for=\"su_pfx\">" .
             $lc_str['su_pfx'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"su_pfx\" id=\"su_pfx\" value=\"$su_pfx\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Suffix
             "                <p>\n" .
             "                    <label for=\"su_sfx\">" .
             $lc_str['su_sfx'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"su_sfx\" id=\"su_sfx\" value=\"$su_sfx\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Page title
             "                <p>\n" .
             "                    <label for=\"page\">" .
             $lc_str['page'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"page\" id=\"page\" value=\"$page\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** META description
             "                <p>\n" .
             "                    <label for=\"meta_d\">" .
             $lc_str['meta_d'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"meta_d\" id=\"meta_d\" value=\"$meta_d\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** META keywords
             "                <p>\n" .
             "                    <label for=\"meta_k\">" .
             $lc_str['meta_k'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"meta_k\" id=\"meta_k\" value=\"$meta_k\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Language
             "                <p>\n" .
             "                    <label for=\"lc\">" .
             $lc_str['lc'] . "</label>\n" .
             "                    <span>" . $lc_str['current'] . " " .
             "$lc</span> \n" .
             "                    <select name=\"lc\" " .
             "id=\"lc\" title=\"" . $lc_str['sel_tip'] . "\">\n" .
             "                        <option value=\"select\" " .
             "title=\"" . $lc_str['sel_tip'] . "\" selected " .
             "disabled>" . $lc_str['sel'] . "</option>\n";

        foreach ($lc_ls as $item) {
            $lc_val = basename($item);
            $lc_val = str_replace(".php", "", $lc_val);

            echo "                        <option value=" .
                 "\"$lc_val\" title=\"" . $lc_str['sel_tip'] .
                 "\">$lc_val</option>\n";
        }

        unset($item);

        echo "                    </select>\n" .
                  "                </p>\n" .

        //** Theme
             "                <p>\n" .
             "                    <label for=\"th\">" .
             $lc_str['th'] . "</label>\n" .
             "                    <span>" . $lc_str['current'] . " " .
             "$th</span> \n" .
             "                    <select name=\"th\" " .
             "id=\"th\" title=\"" . $lc_str['sel_tip'] . "\">\n" .
             "                        <option value=\"select\" " .
             "title=\"" . $lc_str['sel_tip'] . "\" selected " .
             "disabled>" . $lc_str['sel'] . "</option>\n";

        foreach ($th_ls as $item) {
            $th_val = basename($item);
            $th_val = str_replace(".css", "", $th_val);

            echo "                        <option value=\"" .
                 "$th_val\" title=\"" . $lc_str['sel_tip'] . "\">" .
                 "$th_val</option>\n";
        }

        unset($item);

        echo "                    </select>\n" .
             "                </p>\n" .

        //** Theme multi
             "                <p>\n" .
             "                    <label for=\"th_m\">" .
             $lc_str['th_m'] . "</label>\n" .
             "                    <input type=\"checkbox\" " .
             "name=\"th_m\" id=\"th_m\" " .
             "title=\"" . $lc_str['tick'] . "\"";

        if ($th_m === 1) {
            echo " checked ";
        }

        echo "/>\n" .
             "                </p>\n" .

        //** Characters per post
             "                <p>\n" .
             "                    <label for=\"char\">" .
             $lc_str['char'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"char\" id=\"char\" value=\"$char\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Emoji auto conversion
             "                <p>\n" .
             "                    <label for=\"emo\">" .
             $lc_str['emo'] . "</label>\n" .
             "                    <input type=\"checkbox\" " .
             "name=\"emo\" id=\"emo\" " .
             "title=\"" . $lc_str['tick'] . "\"";

        if ($emo === 1) {
            echo " checked ";
        }

        echo "/>\n" .
             "                </p>\n" .

        //** Refresh rate
             "                <p>\n" .
             "                    <label for=\"rate\">" .
             $lc_str['rate'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"rate\" id=\"rate\" value=\"$rate\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Timeout
             "                <p>\n" .
             "                    <label for=\"out\">" .
             $lc_str['out'] . "</label>\n" .
             "                    <input type=\"checkbox\" " .
             "name=\"out\" id=\"out\" " .
             "title=\"" . $lc_str['tick'] . "\"";

        if ($out === 1) {
            echo " checked ";
        }

        echo "/>\n" .
             "                </p>\n" .

        //** Timeout max
             "                <p>\n" .
             "                    <label for=\"out_max\">" .
             $lc_str['out_max'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"out_max\" id=\"out_max\" value=\"$out_max\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Random min
             "                <p>\n" .
             "                    <label for=\"rn_min\">" .
             $lc_str['rn_min'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"rn_min\" id=\"rn_min\" value=\"$rn_min\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Random max
             "                <p>\n" .
             "                    <label for=\"rn_max\">" .
             $lc_str['rn_max'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"rn_max\" id=\"rn_max\" value=\"$rn_max\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Uploads
             "                <p>\n" .
             "                    <label for=\"up\">" .
             $lc_str['up'] . "</label>\n" .
             "                    <input type=\"checkbox\" " .
             "name=\"up\" id=\"up\" title=\"" . $lc_str['tick'] . "\"";

        if ($up === 1) {
            echo " checked ";
        }

        echo "/>\n" .
             "                </p>\n" .

        //** Uploads max size
             "                <p>\n" .
             "                    <label for=\"up_max\">" .
             $lc_str['max'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"up_max\" id=\"up_max\" value=\"$up_max\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Thumbnail max w/h
             "                <p>\n" .
             "                    <label for=\"tn\">" .
             $lc_str['tn'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"tn\" id=\"tn\" value=\"$tn\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Type delete
             "                <p>\n" .
             "                    <label for=\"type_del\">" .
             $lc_str['type_del'] . "</label>\n" .
             "                    <select " .
             "name=\"type_del\" id=\"type_del\" " .
             "title=\"" . $lc_str['sel_tip'] . "\">\n" .
             "                        <option value=\"select\" " .
             "title=\"" . $lc_str['sel_tip'] . "\" selected " .
             "disabled>" . $lc_str['sel'] . "</option>\n";

        foreach ($type as $item) {
            echo "                        <option " .
                 "value=\"$item\" title=\"" .
                 $lc_str['sel_del'] . "\">$item</option>\n";
        }

        unset($item);

        echo "                    </select>\n" .
             "                </p>\n" .

        //** Type add
             "                <p>\n" .
             "                    <label for=\"type_add\">" .
             $lc_str['type_add'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"type_add\" id=\"type_add\" " .
             "title=\"" . $lc_str['type_add_t'] . "\"/>\n" .
             "                </p>\n" .

        //** Auto remove old files
             "                <p>\n" .
             "                    <label for=\"rm\">" .
             $lc_str['rm'] . "</label>\n" .
             "                    <input type=\"checkbox\" " .
             "name=\"rm\" id=\"rm\" title=\"" . $lc_str['tick'] . "\"";

        if ($rm === 1) {
            echo " checked ";
        }

        echo "/>\n" .
             "                </p>\n" .

        //** Days to keep files
             "                <p>\n" .
             "                    <label for=\"rm_max\">" .
             $lc_str['rm_max'] . "</label>\n" .
             "                    <input type=\"text\" " .
             "name=\"rm_max\" id=\"rm_max\" value=\"$rm_max\" " .
             "title=\"" . $lc_str['edit'] . "\"/>\n" .
             "                </p>\n" .

        //** Close superuser screen
             "                <div class=\"close\">\n" .
             "                    <input type=\"submit\" " .
             "name=\"close\" id=\"close\" value=\"x\" " .
             "title=\"" . $lc_str['close'] . "\"/>\n";

        if (is_file($log)) {
            echo "                    <input type=\"submit\" " .
                 "name=\"reset\" id=\"reset\" value=\"0\" " .
                 "title=\"" . $lc_str['reset'] . "\"/>\n";
        }

        echo "                    <input type=\"submit\" " .
             "name=\"update\" id=\"update\" value=\"&gt;\" " .
             "title=\"" . $lc_str['update'] . "\"/>\n" .
             "                </div>\n" .
             "            </article>\n";
    }
} else {

    /**
    ********************************************************************
    *                                                     Login screen *
    ********************************************************************
    */

    echo "            <article class=\"block\" id=\"login\">\n" .
         "                <h1>" . $lc_str['welcome'] . "</h1>\n";

    //** Cookie
    if (!isset($_COOKIE['ac_cookie'])) {
        echo "                <h2>" . $lc_str['perm'] . "</h2>\n" .
             "                <p>\n" .
             "                    " . $lc_str['cook_txt'] . "\n" .
             "                    <input type=\"checkbox\" " .
             "name=\"perm\" id=\"perm\" " .
             "title=\"" . $lc_str['perm_tip'] . "\"/> \n" .
             "                </p>\n" .
             "                <p>" . $lc_str['cook_del'] . "</p>\n";
    }

    //** Info
    echo "                <p>" . $lc_str['name_txt'] . "</p>\n" .
         "                <noscript>\n" .
         "                    <h2>" . $lc_str['js'] . "</h2>\n" .
         "                    <p>" . $lc_str['js_txt'] . "</p>\n" .
         "                </noscript>\n" .
         "            </article>\n" .
         "            <nav class=\"block login\">\n" .

    //** Name
         "                <div>\n" .
         "                    <label for=\"name\">" .
         $lc_str['name'] . "</label>\n" .
         "                    <input type=\"text\" name=\"name\" " .
         "id=\"name\" maxlength=\"16\" " .
         "title=\"" . $lc_str['name_tip'] . "\"/> \n" .

    //** Login
         "                    <input type=\"submit\" name=\"login\" " .
         "value=\"&gt;\" title=\"" . $lc_str['login'] . "\"/>\n" .
         "                </div>\n" .
         "            </nav>\n";
}

/**
 ***********************************************************************
 *                                                          End markup *
 ***********************************************************************
 */

echo "        </form>\n" .
     "    </body>\n" .
     "</html>\n";

//** Looloo time
ob_flush();
flush();
